### ISSUE TITLE
PlayMat job error when there are whitespaces in current path

### ISSUE THREAD

**Issue by ijon-tichy** [elmar-peise/ELAPS#1]
*.err file shows something like:

bash: Zeile 5: /home/[...]/[dirname]: Datei oder Verzeichnis nicht gefunden
ERROR 127

where [dirname] is only showing the part of the actual directory name up to the first whitespace
removing all whitespaces from the current path and rebuilding the sampler fixed this issue

**Comment by elmar-peise** [comment]
Fixed by 76f67553c0eee0c96a7c1c57a779ebbaac95be76.
