### ISSUE TITLE
Viewer: wrong efficiency calculation when using omp

### ISSUE THREAD

**Issue by ijon-tichy** [elmar-peise/ELAPS#4]
dgemm with "#omp for j=1:10" and 4 threads give about 25Gflops/s, sequential is about 7.5
displayed efficiency for the omp case is at ~7.8% which should rather be ~78%

**Comment by elmar-peise** [comment]
If your sampler is correctly configured, your described setup should use min(40, #cores) as a reference for efficiency.
Can you give some more details on what you're running? CPU, #cores, ...
What's the flops/cycle you reach?

**Comment by elmar-peise** [comment]
Issue is insufficiently described and cannot be reproduced.
