### ISSUE TITLE
PlayMat converts i-1 to [<class 'elaps.symbolic.Plus'>] for BasicCalls

### ISSUE THREAD

**Issue by bjoernads** [elmar-peise/ELAPS#5]
Expressions that contains '+' or '-' are converted to **[<class 'elaps.symbolic.Plus'>]** in the *.calls file for **BasicCall** routines like _dorgtr_ or _dsycon_.

**Comment by elmar-peise** [comment]
Fixed by 518a9fd1e3ac8fc4ac1aa650e14b1bec45568fd0
